run_cmd: "iflow -p ${prompt} --yolo"

project_path: "/testbed"

agent_run_timeout: 3600

runtime_env_config:
  type: node
  custom_install_cmd: "npm i -g https://xrl-sandbox-bucket.oss-cn-hangzhou.aliyuncs.com/wanqi-test/iflow-ai-iflow-cli-0.4.9-beta-20251219-v2_agentv1.tgz"

env:
  IFLOW_API_KEY: "1C330YAIQG" # whale key
  IFLOW_SEARCH_KEY: "sk-020c4155037918ef55c692896f64f6c6"
  IFLOW_BASE_URL: "https://whale-wave.alibaba-inc.com/api/v2/services/aigc/text-generation/v1" # whale url
  IFLOW_MODEL_NAME: "GLM-4.6"


